Remove byte size field from accessor
toku-sa-n/accessor pull request #45
Opened 2023-10-03 14:18 UTC by paulsohn

For a single-element accessor, its size is determined with const function `mem::size_of::<T>()`. No need to store it in a field.

2023-10-04 09:49 UTC, toku-sa-n requested changes
Thanks. Could you apply `rustfmt`, and add this change to `CHANGELOG.md`?

2023-10-06 14:02 UTC, paulsohn commented
`cargo fmt` has been already applied.

2023-10-06 14:52 UTC, toku-sa-n commented
My apologies. I thought CI failed due to the format issue, but the actual cause was a clippy issue. I sent a PR to fix it. After that, could you update the PR? Then I'll merge it.

2023-10-07 01:48 UTC, toku-sa-n approved these changes

2023-10-07 08:52 UTC, merged